### PR TITLE
Update Reference Server to support multi-versions

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by rhc54** [comment]
@ggouaillardet Can you think of any reason why the one compiler would have failed? I can't see a reason behind it.

**Comment by ggouaillardet** [comment]
@rhc54 it looks like something hanged. that sometimes occurs with travis-ci ...
i suggest you manually trigger an other build and see how things go.

note there is a non fatal error (cannot link the test program) with all compilers

**Comment by rhc54** [comment]
Hmmm...I'm at a loss to understand the link issue as I cannot replicate it. It looks like it isn't somehow including libpsrvopen-pal, yet pcc clearly shows it (at least, on my system):
```
$ pcc --showme
gcc -I/home/common/pmix/build/psrv/include/openmpi
-I/home/common/pmix/build/psrv/include/pmix/opal/mca/hwloc/hwloc2a/hwloc/include
-I/home/common/pmix/build/psrv/include/pmix/opal/mca/event/libevent2022/libevent
-I/home/common/pmix/build/psrv/include/pmix/opal/mca/event/libevent2022/libevent/include
-I/home/common/pmix/build/psrv/include -pthread -Wl,-rpath
-Wl,/home/common/pmix/build/psrv/lib -Wl,--enable-new-dtags -lpmix
-L/home/common/pmix/build/psrv/lib -lpsrvropen-rte -lpsrvropen-pal -lpmix
```
You have any thoughts? I'm unfamiliar with the Travis environment - I wonder if this "failure" has been occurring undetected for some time?

**Comment by ggouaillardet** [comment]
yeah, i cannot reproduce it here too, and logs cannot be retrieved anymore from travis.

i ll issue a new PR with a bunch of verbose debug to investigate that.

**Comment by rhc54** [comment]
Thanks - deeply appreciated

**Comment by ggouaillardet** [comment]
no problem.

i was able to reproduce the issue on the very same distro (ubuntu 14.04 aka trusty) and issued #27 to fix that.

i simply removed `-lpsrvropen-rte` from the dependencies, and the trailing `-lpmix` too, and that fixed the issue. and i have no idea why that worked, especially since `-lprsrvropen-pal` just follows.

i noted two more issues
 - `--oversubscribe` does not seem to work (not enough slots ... on a single core travis VM)
 - `prun app` simply hangs when `app` does not exist (same issue with Open MPI master)

**Comment by rhc54** [comment]
Many thanks! I'll resolve the two issues you cite.

**Pull request merged**
