### PR TITLE
Sync to upstream master

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by rhc54** [comment]
Fixes #43

**Comment by bgoglin** [comment]
Thanks, applying 322f6c5056fc484edc34f0e8eb7d536bf13366b5 to OMPI 3.1.0rc3 indeed fixes my issue.

**Comment by bgoglin** [comment]
I take that back, we are always in --rank-by socket now:
```
-n 4 --map-by socket --rank-by socket --bind-to core
2.1.3
 MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././././././.][./././././././././././.]
 MCW rank 1 bound to socket 1[core 12[hwt 0]]: [./././././././././././.][B/././././././././././.]
 MCW rank 2 bound to socket 0[core 1[hwt 0]]: [./B/./././././././././.][./././././././././././.]
 MCW rank 3 bound to socket 1[core 13[hwt 0]]: [./././././././././././.][./B/./././././././././.]
3.1.0rc3+patch
 MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././././././.][./././././././././././.]
 MCW rank 1 bound to socket 1[core 12[hwt 0]]: [./././././././././././.][B/././././././././././.]
 MCW rank 2 bound to socket 0[core 1[hwt 0]]: [./B/./././././././././.][./././././././././././.]
 MCW rank 3 bound to socket 1[core 13[hwt 0]]: [./././././././././././.][./B/./././././././././.]
=> OK 

-n 4 --map-by socket --rank-by core --bind-to core
2.1.3
 MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././././././.][./././././././././././.]
 MCW rank 1 bound to socket 0[core 1[hwt 0]]: [./B/./././././././././.][./././././././././././.]
 MCW rank 2 bound to socket 1[core 12[hwt 0]]: [./././././././././././.][B/././././././././././.]
 MCW rank 3 bound to socket 1[core 13[hwt 0]]: [./././././././././././.][./B/./././././././././.]
3.1.0rc3+patch
 MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././././././.][./././././././././././.]
 MCW rank 1 bound to socket 1[core 12[hwt 0]]: [./././././././././././.][B/././././././././././.]
 MCW rank 2 bound to socket 0[core 1[hwt 0]]: [./B/./././././././././.][./././././././././././.]
 MCW rank 3 bound to socket 1[core 13[hwt 0]]: [./././././././././././.][./B/./././././././././.]
=> not OK, 3.1.0rc3+patch still ranks by socket

-n 8 --map-by socket --rank-by numa --bind-to core
2.1.3
 MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././././././.][./././././././././././.]
 MCW rank 1 bound to socket 0[core 1[hwt 0]]: [./B/./././././././././.][./././././././././././.]
 MCW rank 2 bound to socket 1[core 12[hwt 0]]: [./././././././././././.][B/././././././././././.]
 MCW rank 3 bound to socket 1[core 13[hwt 0]]: [./././././././././././.][./B/./././././././././.]
 MCW rank 4 bound to socket 0[core 2[hwt 0]]: [././B/././././././././.][./././././././././././.]
 MCW rank 5 bound to socket 0[core 3[hwt 0]]: [./././B/./././././././.][./././././././././././.]
 MCW rank 6 bound to socket 1[core 14[hwt 0]]: [./././././././././././.][././B/././././././././.]
 MCW rank 7 bound to socket 1[core 15[hwt 0]]: [./././././././././././.][./././B/./././././././.]
 (that's correct, we have 2 NUMA nodes per socket, with interleaved cores)
3.1.0rc3+patch
 MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././././././.][./././././././././././.]
 MCW rank 1 bound to socket 1[core 12[hwt 0]]: [./././././././././././.][B/././././././././././.]
 MCW rank 2 bound to socket 0[core 1[hwt 0]]: [./B/./././././././././.][./././././././././././.]
 MCW rank 3 bound to socket 1[core 13[hwt 0]]: [./././././././././././.][./B/./././././././././.]
 MCW rank 4 bound to socket 0[core 2[hwt 0]]: [././B/././././././././.][./././././././././././.]
 MCW rank 5 bound to socket 1[core 14[hwt 0]]: [./././././././././././.][././B/././././././././.]
 MCW rank 6 bound to socket 0[core 3[hwt 0]]: [./././B/./././././././.][./././././././././././.]
 MCW rank 7 bound to socket 1[core 15[hwt 0]]: [./././././././././././.][./././B/./././././././.]
=> not OK, 3.1.0rc3+patch still ranks by socket
```

Additionally, --display-devel-map in 2.1.3 shows the binding just like --report-bindings,
while it always shows UNBOUND in 3.1.0rc3+patch.

**Comment by rhc54** [comment]
I'm afraid I don't have any time right now to continue looking at it. I'd suggest checking the ranking policy to ensure it has been correctly set as I don't see anything in rmaps_base_ranking.c that would lock us to a particular ranking algo.

**Comment by rhc54** [comment]
@bgoglin I believe this is fixed now in OMPI and I will sync it here. As for display-devel-map, it does appear to be working and showing bindings. However, recall that when we went to distributed mapping, each daemon only knows the binding for the procs local to it. Thus, you'll see an output from each daemon, with the bindings for procs on all other nodes shown as unbound.

**Comment by bgoglin** [comment]
@rhc54 Sorry I couldn't test earlier. I can't even test things anymore, mpiexec hangs after launching 2 procs whenever I pass --map-by socket or rank-by socket (no problem with core instead of socket).
Tested with 3.1.0rc3 + your patches and master nightly snapshot. That's on a single 24-core host with a command-line like this:
```
~/openmpi-master-201803300306-44a1c78/build/install/bin/mpiexec -H $SLURM_NODELIST --display-devel-map --mca rmaps_base_verbose 100 --bind-to core --map-by socket hostname
```
I get the output of all 24 procs from --display-devel-map. But hostname and --report-binding only appear for 2 processes. Then mpiexec hangs. If I remove --map-by socket, all 24 procs are launched.

**Comment by rhc54** [comment]
Afraid I'm out of ideas - I can't replicate that on any system I can access. I suspect it is in some kind of infinite loop in the ranking algo due to the particulars of your topology - should be easy to track down, I would think.

**Comment by bgoglin** [comment]
It's likely not an infinite loop since I don't see any process wasting 100% CPU. Also, given that --display-devel-map looks good, where should I look? Where's the code responsible for actually launching procs once mapping/ranking/binding/displaying is done?

**Comment by bgoglin** [comment]
Finally got some time to debug this. The issue is that 22 ranks out of 24 do not have local_rank/node_rank/app_rank initialized. Hence they are not launched.

Likely caused by rank_by() only ranking 2 processes out of 24. Others are ignored because we get NULL from:
```
  obj = (hwloc_obj_t)opal_pointer_array_get_item(&objs, i);
```
That makes sense because there are only 2 sockets on that machine (and I am ranking by socket).

Do we need some sort of round-robin to ask for socket i%numsocket instead of i?

**Comment by rhc54** [comment]
Ohhhh...duh. Thanks for doing the detective work. I'll fix it.

**Comment by rhc54** [comment]
@bgoglin See https://github.com/open-mpi/ompi/pull/5108

**Pull request merged**
